const atoms = [
    {
        architecture: "Bonnel 45 nm",
        type: "Nettop",
        platform: "N/A",
        codename: "Diamondville",
        name: "Atom 330, 230",
        chipset: "945GC (Lakeport)",
        graphics: "GMA 950",
        ark: "http://ark.intel.com/products/codename/32202/Diamondville"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Netbook",
        platform: "Navy Pier",
        codename: "Diamondville",
        name: "Atom N280, N270",
        chipset: "945GSE (Calistoga)",
        graphics: "GMA 950",
        ark: "http://ark.intel.com/products/codename/32202/Diamondville"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Tablet",
        platform: "Menlow",
        codename: "Silverthorn",
        name: "Atom Z5xx",
        chipset: "UL11x/US15x (Poulsbo SCH)",
        graphics: "GMA 500 - PowerVR SGX535",
        ark: "http://ark.intel.com/products/codename/24976/Silverthorne"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Nettop",
        platform: "Luna Pier",
        codename: "Pineview",
        codenameEx: "Pineview-D",
        name: "Atom D525, D510, D425, D410",
        chipset: "ICH8M",
        graphics: "GMA 3150 (Gen 3)",
        ark: "http://ark.intel.com/products/codename/32201/Pineview"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Netbook",
        platform: "Luna Pier",
        codename: "Pineview",
        codenameEx: "Pineview-M",
        name: "Atom N455, N450",
        chipset: "ICH8M",
        graphics: "GMA 3150 (Gen 3)",
        ark: "http://ark.intel.com/products/codename/32201/Pineview"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Nettop",
        platform: "Pine Trail",
        platformEx: "Pine Trail-D",
        codename: "Pineview",
        codenameEx: "Pineview-D",
        name: "Atom D525, D510, D425, D410",
        chipset: "NM10 (Tiger Point)",
        graphics: "GMA 3150 (Gen 3)",
        ark: "http://ark.intel.com/products/codename/32201/Pineview"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Netbook",
        platform: "Pine Trail",
        platformEx: "Pine Trail-M",
        codename: "Pineview",
        codenameEx: "Pineview-M",
        name: "Atom N570, N550, N47x, N45x",
        chipset: "NM10 (Tiger Point)",
        graphics: "GMA 3150 (Gen 3)",
        ark: "http://ark.intel.com/products/codename/32201/Pineview"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Tablet",
        platform: "Oak Trail",
        codename: "Lincroft",
        name: "Atom Z670, Z650",
        chipset: "SM35 (Whitney Point)",
        graphics: "GMA 600 - PowerVR SGX",
        ark: "http://ark.intel.com/products/codename/29967/Lincroft"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Basic Tablet",
        platform: "Moorestown",
        codename: "Lincroft",
        name: "Atom Z6xx",
        chipset: "MP20/MP30 (Langwell)",
        graphics: "GMA 600 - PowerVR SGX",
        ark: "http://ark.intel.com/products/codename/29967/Lincroft"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Embedded",
        platform: "Queens Bay",
        codename: "Tunnel Creek",
        name: "Atom E6xx(T)",
        chipset: "EG20T (Topcliff)",
        graphics: "?",
        ark: "http://ark.intel.com/products/codename/37567/Tunnel-Creek"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "FPGA",
        platform: "?",
        codename: "Stellarton",
        name: "Atom E6xxC(T)",
        chipset: "EG20T (Topcliff)",
        graphics: "Altera FPGA",
        ark: "http://ark.intel.com/products/codename/42360/Stellarton"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Consumer Electronics",
        platform: "?",
        codename: "Sodaville",
        name: "Atom CE41x0",
        chipset: "?",
        graphics: "GMA 500 - SGX 535",
        ark: "http://ark.intel.com/products/codename/36894/Sodaville"
    },
    {
        architecture: "Bonnel 45 nm",
        type: "Consumer Electronics",
        platform: "?",
        codename: "Groveland",
        name: "Atom CE42x0",
        chipset: "?",
        graphics: "GMA 500 - SGX 535"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Nettop",
        platform: "Cedar Trail",
        platformEx: "Cedar Trail-D",
        codename: "Cedarview",
        codenameEx: "Cedarview-D",
        name: "Atom D2700, D2550, D2500",
        chipset: "NM10 (Tiger Point)",
        graphics: "GMA 3600/3650 - PowerVR SGX545",
        ark: "http://ark.intel.com/products/codename/37505/Cedarview"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Netbook",
        platform: "Cedar Trail",
        platformEx: "Cedar Trail-M",
        codename: "Cedarview",
        codenameEx: "Cedarview-M",
        name: "Atom N2800, N2600",
        chipset: "NM10 (Tiger Point)",
        graphics: "GMA 3600/3650 - PowerVR SGX545",
        ark: "http://ark.intel.com/products/codename/37505/Cedarview"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Tablet",
        platform: "Clover Trail",
        codename: "Cloverview",
        codenameAlt: "Clover Trail SoC",
        name: "Atom Z2760",
        chipset: "-",
        graphics: "PowerVR SGX545",
        ark: "http://ark.intel.com/products/codename/53606/Cloverview"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Basic Tablet",
        platform: "Clover Trail+",
        codename: "Cloverview+",
        codenameAlt: "Clover Trail+ SoC",
        name: "Atom Z2580, Z2560, Z2520",
        chipset: "-",
        graphics: "PowerVR SGX544MP2",
        ark: "http://ark.intel.com/products/codename/53606/Cloverview"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Smartphone",
        platform: "Medfield",
        codename: "Penwell",
        codenameAlt: "Medfield SoC",
        name: "Atom Z2480, Z2460",
        chipset: "-",
        graphics: "PowerVR SGX540",
        ark: "http://ark.intel.com/products/codename/43824/Penwell"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Basic Smartphone",
        platform: "Lexington",
        codename: "Penwell",
        codenameAlt: "Lexington SoC",
        name: "Atom Z2420",
        chipset: "-",
        graphics: "PowerVR SGX540",
        ark: "http://ark.intel.com/products/codename/43824/Penwell"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Consumer Electronics",
        platform: "Evansport",
        codename: "Berryville",
        name: "Atom CE53xx",
        chipset: "-",
        graphics: "",
        connectivity: "SATA: 2",
        sata: "3.0 x2"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Server",
        platform: "Bordenville",
        codename: "Centerton",
        name: "Atom S12x0",
        chipset: "-",
        graphics: "?",
        ark: "http://ark.intel.com/products/codename/60105/Centerton"
    },
    {
        architecture: "Saltwell 32 nm",
        type: "Communications & Storage",
        platform: "?",
        codename: "Briarwood",
        name: "Atom S12x9",
        chipset: "-",
        graphics: "?",
        ark: "http://ark.intel.com/products/codename/49838/Briarwood"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Nettop",
        platform: "Bay Trail",
        platformEx: "Bay Trail-D",
        platformAlt: "Balboa Pier",
        codename: "Bay Trail",
        codenameAlt: "Valleyview-D",
        name: "Pentium J2xxx/Celeron J1xxx",
        chipset: "-",
        graphics: "Intel Gen 7",
        connectivity: "PCIe 2.0 x4, SATA 6.0 x2, USB 2.0/3.0 x5",
        pcie: "2.0 x4",
        sata: "6.0 x2",
        usb: "3.0 x5",
        ark: "http://ark.intel.com/products/codename/55844/Bay-Trail"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Netbook",
        platform: "Bay Trail",
        platformEx: "Bay Trail-M",
        codename: "Bay Trail",
        codenameAlt: "Valleyview-M",
        name: "Pentium N35xx/Celeron N2xxx",
        chipset: "-",
        graphics: "Intel Gen 7",
        connectivity: "PCIe 2.0 x4, SATA 6.0 x2, USB 2.0/3.0 x5",
        pcie: "2.0 x4",
        sata: "6.0 x2",
        usb: "3.0 x5",
        ark: "http://ark.intel.com/products/codename/55844/Bay-Trail"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Embedded",
        platform: "Bay Trail",
        platformEx: "Bay Trail-I",
        codename: "Bay Trail",
        codenameAlt: "Valleyview-I",
        name: "Atom E38xx",
        chipset: "-",
        graphics: "Intel Gen 7",
        ark: "http://ark.intel.com/products/codename/55844/Bay-Trail"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Tablet",
        platform: "Bay Trail",
        platformEx: "Bay Trail-T",
        codename: "Bay Trail",
        codenameAlt: "Valleyview-T/Valleyview 2",
        name: "Atom Z3770(D), Z3740(D)",
        chipset: "-",
        graphics: "Intel Gen 7",
        ark: "http://ark.intel.com/products/codename/55844/Bay-Trail"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Basic Tablet",
        platform: "Moorefield",
        codename: "Moorefield",
        codenameAlt: "Anniedale",
        name: "Atom Z3580, Z3560",
        chipset: "-",
        graphics: "PowerVR G6430",
        ark: "http://ark.intel.com/products/codename/71167/Moorefield"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Smartphone",
        platform: "Merrifield",
        codename: "Merrifield",
        codenameAlt: "Tangier",
        name: "Atom Z3480, Z3460",
        chipset: "-",
        graphics: "PowerVR G6400",
        ark: "http://ark.intel.com/products/codename/41559/Merrifield"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Basic Smartphone",
        platform: "Slayton",
        codename: "Slayton",
        name: "Canceled",
        chipset: "-",
        graphics: "PowerVR SGX544"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Server",
        platform: "Edisonville",
        codename: "Avoton",
        name: "Atom C2xx0",
        chipset: "-",
        graphics: "",
        ark: "http://ark.intel.com/products/codename/54859/Avoton"
    },
    {
        architecture: "Silvermont 22 nm",
        type: "Communications & Storage",
        platform: "Edisonville",
        codename: "Rangeley",
        name: "Atom C2xx8",
        chipset: "-",
        graphics: "",
        connectivity: "PCIe 2.0 x16, SATA 6.0 x2, SATA 3.0 x4, USB 2.0 x4, 4x1 or 4x2.5 GbE",
        pcie: "2.0 x4",
        sata: "3.0 x4, 6.0 x2",
        usb: "3.0 x5",
        ark: "http://ark.intel.com/products/codename/60191/Rangeley"
    },
    {
        architecture: "Airmont 14 nm",
        type: "Nettop",
        platform: "Braswell",
        codename: "Braswell",
        name: "Pentium J37xx/Celeron J3xxx",
        chipset: "-",
        graphics: "Intel Gen 8",
        connectivity: "PCIe 2.0 x4, SATA 6.0 x2, USB 2.0/3.0 x5",
        pcie: "2.0 x4",
        sata: "6.0 x2",
        usb: "3.0 x5",
        ark: "http://ark.intel.com/products/codename/66094/Braswell"
    },
    {
        architecture: "Airmont 14 nm",
        type: "Netbook",
        platform: "Braswell",
        codename: "Braswell",
        name: "Pentium N37xx/Celeron N3xxx",
        chipset: "-",
        graphics: "Intel Gen 8",
        connectivity: "PCIe 2.0 x4, SATA 6.0 x2, USB 2.0/3.0 x5",
        pcie: "2.0 x4",
        sata: "6.0 x2",
        usb: "3.0 x5",
        ark: "http://ark.intel.com/products/codename/66094/Braswell"
    },
    {
        architecture: "Airmont 14 nm",
        type: "Embedded",
        platform: "Braswell",
        codename: "Braswell",
        name: "Atom x5-E8000",
        chipset: "-",
        graphics: "Intel Gen 8",
        ark: "http://ark.intel.com/products/codename/66094/Braswell"
    },
    {
        architecture: "Airmont 14 nm",
        type: "Tablet",
        platform: "Cherry Trail",
        platformEx: "Cherry Trail-T",
        codename: "Cherry Trail",
        codenameAlt: "Cherryview",
        name: "Atom x7-Z87xx, x5-Z85xx, x5-Z83xx",
        chipset: "-",
        graphics: "Intel Gen 8",
        connectivity: "PCIe 2.0 x2, USB 3.0 x3",
        pcie: "2.0 x2",
        usb: "3.0 x3",
        ark: "http://ark.intel.com/products/codename/46629/Cherry-Trail"
    },
    {
        architecture: "Airmont 14 nm",
        type: "Smartphone",
        platform: "Binghamton",
        codename: "Binghamton",
        name: "Canceled",
        chipset: "-",
        graphics: ""
    },
    {
        architecture: "Airmont 14 nm",
        type: "Basic Smartphone",
        platform: "Riverton",
        codename: "Riverton",
        name: "Canceled",
        chipset: "-",
        graphics: "DC GPU"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Server",
        platform: "?",
        codename: "Denverton",
        name: "Atom C3xx0",
        chipset: "-",
        graphics: "",
        ark: "?"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Nettop",
        platform: "Apollo Lake",
        codename: "Apollo Lake",
        name: "Pentium J4205, Celeron J3455, J3355",
        chipset: "-",
        graphics: "Intel Gen 9",
        ark: "http://ark.intel.com/products/codename/80644/Apollo-Lake"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Netbook",
        platform: "Apollo Lake",
        codename: "Apollo Lake",
        name: "Pentium N4200, Celeron N3450, N3350",
        chipset: "-",
        graphics: "Intel Gen 9",
        ark: "http://ark.intel.com/products/codename/80644/Apollo-Lake"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Embedded",
        platform: "Apollo Lake",
        codename: "Apollo Lake",
        name: "Atom x7-E3950, x5-E3940, E3930",
        chipset: "-",
        graphics: "Intel Gen 9",
        ark: "http://ark.intel.com/products/codename/80644/Apollo-Lake"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Tablet",
        platform: "Willow Trail",
        codename: "Broxton",
        codenameAlt: "Willowview/Willow Trail SoC",
        name: "Cancelled",
        chipset: "-",
        graphics: "Intel Gen 9"
    },
    {
        architecture: "Goldmont 14 nm",
        type: "Basic Tablet",
        platform: "Morganfield",
        codename: "Morganfield",
        codenameAlt: "Broxton (later reused or rather moved to Willow Trail, check what was predecessor)",
        name: "Cancelled",
        chipset: "-",
        graphics: "Intel Gen 9"
    },
    {
        architecture: "Goldmont Plus 14 nm",
        type: "Nettop",
        platform: "Gemini Lake",
        codename: "Gemini Lake",
        name: "Pentium Silver J5005, Celeron J4105, J4005",
        chipset: "-",
        graphics: "Intel Gen 9",
        ark: "http://ark.intel.com/products/codename/83915/Gemini-Lake"
    },
    {
        architecture: "Goldmont Plus 14 nm",
        type: "Netbook",
        platform: "Gemini Lake",
        codename: "Gemini Lake",
        name: "Pentium Silver N5000, Celeron N4100, N4000",
        chipset: "-",
        graphics: "Intel Gen 9",
        ark: "http://ark.intel.com/products/codename/83915/Gemini-Lake"
    },
    {
        architecture: "Silvermont 28 nm",
        type: "Basic Tablet",
        platform: "SoFIA LTE",
        codename: "-",
        name: "Atom x3-C3445/C3405",
        chipset: "-",
        graphics: "ARM Mali T720 MP2",
        ark: "http://ark.intel.com/products/codename/80013/SoFIA-LTE"
    },
    {
        architecture: "Silvermont 28 nm",
        type: "Smartphone",
        platform: "SoFIA 3G-R",
        codename: "-",
        name: "Atom x3-C3230RK/C3200RK",
        chipset: "-",
        graphics: "ARM Mali 450 MP4",
        ark: "http://ark.intel.com/products/codename/84260/SoFIA-3G-R"
    },
    {
        architecture: "Silvermont 28 nm",
        type: "Basic Smartphone",
        platform: "SoFIA 3G",
        codename: "-",
        name: "Atom x3-C3130",
        chipset: "-",
        graphics: "ARM Mali 400 MP2",
        ark: "http://ark.intel.com/products/codename/80011/SoFIA-3G"
    }
];